version: '3.8'

services:

  #PHP Service
  app:
    build:
      context: .
    image: api-precpago
    container_name: precpago_app
    restart: unless-stopped
    tty: true
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: https://production-url.com
      LOG_LEVEL: error
      RABBITMQ_HOST: precpago_rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_VHOST: /
    working_dir: /var/www/html/
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./:/var/www/html/
    networks:
      - app-network

  #NGINX
  webserver:
    image: nginx:alpine
    container_name: precpago_webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - 8181:8181
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: precpago_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3


#Docker Networks
networks:
  app-network:
    driver: bridge